=== instartds/deshin_mes_info/WebContent/WEB-INF/classes/foren/conf/excel/excel-upload.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!-- 
	 Excel Upload Configuration
	 Version : 1.0	(2012.05.30)
	 Author : Kim Sang Joon@TLab
-->
<!-- 
	configuration is the root element. 
-->
<!ELEMENT workBook   (sheet)*>
<!ATTLIST workBook
	name CDATA  #REQUIRED
	desc CDATA  #IMPLIED 
	validateService CDATA  #IMPLIED 
>

<!ELEMENT sheet (field)*>
<!ATTLIST sheet
	seq CDATA  #REQUIRED
	name CDATA  #REQUIRED
	validateFormName CDATA #IMPLIED 
	desc CDATA  #IMPLIED 
    sqlId CDATA  #IMPLIED 
	startRow CDATA "0"
>
<!ELEMENT field (samples|comments)*>
<!--
	check 가 true인 필드가 null 이면 import stop
-->
<!ATTLIST field 
	col 	CDATA  #REQUIRED 
	name CDATA  #REQUIRED  
	title CDATA  #IMPLIED 
	type (string|number|integer|date) "string"  
	check (true|false) "false"  
	required (true|false) "false" 
	desc CDATA  #IMPLIED 
	align (center|auto) "auto" >

<!ELEMENT samples (sample)*>
<!ELEMENT sample (#PCDATA)>

<!ELEMENT comments (#PCDATA)>

=== instartds/deshin_mes_info/src/resources/foren/conf/excel/upload/s_hpa350ukrv_yp.xml
<?xml version="1.0" encoding="UTF-8"  ?>
<!DOCTYPE excelUpload PUBLIC
         "-//TLab//DTD excep upload config XML V1.0//EN"
         "../excel-upload.dtd">
<workBook name="s_hpa350ukr_yp" desc="TEMPLATE_HPA350"  validateService="s_hpa350ukr_ypService.excelValidate" >
    <sheet seq="0" name="엑셀업로드" startRow="1" sqlId="s_hpa350ukr_ypServiceImpl.insertExcelUpload" validateFormName="s_hpa350ukr_yp">
        <field col="0" 		name="PAY_YYYYMM"		title="급여년월"		     type="string"   check="true">	</field>
		<field col="1"		name="PERSON_NUMB"		title="사번"			     type="string">  </field>
		<field col="2"		name="WAGES_DEDHIR"		title="고용보험"			 type="integer">  </field>
		<field col="3"		name="BUSI_SHARE_I"		title="고용보험 회사부담금"	     type="integer">  </field>
		<field col="4"		name="WAGES_DEDANU"		title="국민연금"			 type="integer">  </field>
		<field col="5"		name="ANU_BASE_I2"		title="국민연금 회사부담금"	     type="integer">  </field>
		<field col="6"		name="WAGES_DEDMED"		title="건강보험"			 type="integer">  </field>
        <field col="7"      name="MED_I2"           title="건강보험 회사부담금"       type="integer">  </field>
        <field col="8"      name="WAGES_DEDLCI"     title="장기요양보험"           type="integer">  </field>
        <field col="9"      name="WORKER_COMPEN_I"  title="장기요양보험 회사부담금"     type="integer">  </field>
        <field col="10"     name="OLD_MED_COMPEN_I" title="산재보험 회사부담금"       type="integer">  </field>
    </sheet>
</workBook>

=== instartds/deshin_mes_info/src/resources/foren/conf/excel/upload/sof102ukrv.xml
<?xml version="1.0" encoding="UTF-8"  ?>
<!DOCTYPE excelUpload PUBLIC
         "-//TLab//DTD excep upload config XML V1.0//EN"
         "../excel-upload.dtd">
<workBook name="sof102ukrv" desc="일괄수주정보"  validateService="sof102ukrvService.excelValidate">
    <sheet seq="0" name="일괄수주정보" startRow="1" sqlId="sof102ukrvServiceImpl.insertExcelSof102ukrv" validateFormName="sof102ukrv">
        <field col="0" name="OUT_DIV_CODE" title="출고사업장" type="string" required="true" check="true"></field>
        <field col="1" name="PO_NUM" title="발주번호" type="string" required="true" check="true"></field>
        <field col="2" name="PO_SEQ" title="발주순번" type="integer"></field>
        <field col="3" name="ITEM_CODE" title="품목코드" type="string" required="true"></field>
        <field col="4" name="ITEM_NAME" title="품목명" type="string"></field>
        <field col="5" name="ORDER_Q" title="품목수량" type="string"></field>
        <field col="6" name="PO_DATE" title="발주일" type="string"></field>
        <field col="7" name="DVRY_DATE" title="납품요청일" type="string"></field>
        <field col="8" name="CUSTOM_CODE" title="회사코드" type="string" required="true"></field>
        <field col="9" name="CUSTOM_NAME" title="회사명" type="string"></field>
        <field col="10" name="DVRY_CUST_CD" title="납품처코드" type="string"></field>
        <field col="11" name="DVRY_CUST_NM" title="납품처명" type="string"></field>
        <field col="12" name="ORDER_UNIT" title="단위" type="string"></field>
        <field col="13" name="MONEY_UNIT" title="통화" type="string"></field>
        <field col="14" name="ORDER_O" title="금액" type="integer"></field>
        <field col="15" name="ORDER_P" title="단가" type="integer"></field>
        <field col="16" name="REMARK" title="비고" type="string"></field>
        
    </sheet>
</workBook>

=== instartds/deshin_mes_info/WebContent/WEB-INF/classes/foren/conf/excel/upload/s_hat910ukr_hs.xml
<?xml version="1.0" encoding="UTF-8"  ?>
<!DOCTYPE excelUpload PUBLIC
         "-//TLab//DTD excep upload config XML V1.0//EN"
         "../excel-upload.dtd">
         
         
<workBook name="s_hat910ukr_hs" desc="근태"  validateService="s_hat910ukr_hsService.excelValidate" >
    <sheet seq="0" name="근태" startRow="1" sqlId="S_Hat910ukr_hsServiceImpl.insertExcelUpload" validateFormName="s_hat910ukr_hs">
		<field col="0"	 	 name="DUTY_YYYYMMDD"	title="근무일자"	  	type="string" check="true">  	</field>
		<field col="1"	 	 name="GROUP_1"		 	title="회사"	  		type="string">    			</field>
		<field col="2"	 	 name="GROUP_2"			title="부서"	  	  	type="string">   				</field>
		<field col="3"	 	 name="GROUP_3"			title="공백1"	  	  	type="string">   				</field>
		<field col="4"	 	 name="GROUP_4"			title="공백2"	  		type="string">   				</field>
		<field col="5"	 	 name="NAME"			title="이름"	  		type="string">   			</field>
		<field col="6"	 	 name="PERSON_NUMB"		title="사번"	  		type="string">   			</field>
		<field col="7"	 	 name="POST_NAME"		title="직급"	  		type="string">   			</field>
		<field col="8"	 	 name="CARD_NUM"		title="카드번호"	  	type="string">   			</field>
		<field col="9"	 	 name="WORK_TEAM"		title="근무조"	  	type="string">   			</field>
		<field col="10"	 	 name="WORK_TYPE"		title="근무스케쥴"	  	type="string">   			</field>
		<field col="11"	 	 name="DUTY_FR"			title="출근시간"	  	type="string">   			</field>
		<field col="12"	 	 name="DUTY_TO"			title="퇴근시간"	  	type="string">   			</field>
		<field col="13"	 	 name="TEMPC_01"		title="여유컬럼1"	  	type="string">   			</field>
		<field col="14"	 	 name="TEMPC_02"		title="여유컬럼2"	  	type="string">   			</field>
		<field col="16"	 	 name="TEMPC_03"		title="여유컬럼3"	  	type="string">   			</field>
		<field col="17"	 	 name="TEMPC_04"		title="여유컬럼4"	  	type="string">   			</field>
		<field col="18"	 	 name="TEMPC_05"		title="여유컬럼5"	  	type="string">   			</field>
		<field col="19"	 	 name="TEMPC_06"		title="여유컬럼6"	  	type="string">   			</field>
		<field col="20"	 	 name="TEMPC_07"		title="여유컬럼7"	  	type="string">   			</field>
		<field col="21"	 	 name="TEMPC_08"		title="여유컬럼8"	  	type="string">   			</field>
		<field col="22"	 	 name="TEMPC_09"		title="여유컬럼9"	 	type="string">   			</field>
		<field col="23"	 	 name="TEMPC_10"		title="여유컬럼10"	  	type="string">   			</field>
		<field col="24"	 	 name="TEMPC_11"		title="여유컬럼11"	  	type="string">   			</field>
    </sheet>
</workBook>
