=== instartds/deshin_mes_info/src/java/test/sourcegen/config/sourceGen_config.dtd
<?xml version="1.0" encoding="UTF-8" ?>


<!ELEMENT packages (package)*>
<!ELEMENT package (program)*>
<!ELEMENT program (methods)>
<!ELEMENT methods (method)*>
<!ELEMENT method EMPTY>

<!ATTLIST packages
	basePackageName 	CDATA  #REQUIRED 
>


<!ATTLIST package
	name 	CDATA  #REQUIRED 
	use       (true|false) #IMPLIED
>

<!ATTLIST program
	baseName 	CDATA  #REQUIRED 
	url			CDATA  #REQUIRED
	desc     CDATA #IMPLIED
>

<!ATTLIST method
	name 	CDATA  #REQUIRED 
	type 	CDATA  #REQUIRED 
	desc     CDATA #IMPLIED
>

=== instartds/deshin_mes_info/WebContent/WEB-INF/classes/test/sourcegen/config/cmi_programList.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sourceGen PUBLIC
         "-//KTNET//DTD SourceGen config XML V1.0//EN"
         "sourceGen_config.dtd">
<!-- <packages basePackageName="unipass.cm.cmi"> -->
<packages basePackageName="test.sourcegen.output">
	<package name="base" use="false">
		<program baseName="CmiBaseManifestAmendType" url="/cm/cmi/base/amendtype">
			<methods>
				<method name="selectAmendTypeList" type="list"></method>
				<method name="selectAmendTypeDetail" type="view"></method>
				<method name="registAmendType" type="form"></method>
			</methods>
		</program>
		<program baseName="CmiBaseEnvironmentSetup" url="/cm/cmi/base/EnvironmentSetup">
			<methods>
				<method name="registEnvironmentSetup" type="list"></method>
			</methods>
		</program>
	</package>
	<package name="manifest">
		<program baseName="CmiManifestVesselOperationSchedule" url="/cm/cmi/manifest/VesselOperationSchedule">
			<methods>
				<method name="selectScheduleList" type="list"></method>
				<method name="selectScheduleDetail" type="view"></method>
				<method name="registSchedule" type="form"></method>
			</methods>
		</program>
	</package>
	
	<package name="cme.loadanddischarge"  use="true">
		<program url="/cm/cme/loadanddischarge" baseName="CmiLoadAndDischargeDischarge">
			<methods>
				<method name="selectMrnList" type="list"></method>
				<method name="selectMrnDetail" type="view"></method>
				<method name="selectCntrList" type="form"></method>
			</methods>
		</program>
				<program baseName="CmiImportManifestAmend" url="/cmi/manifest/Import/ManifestAmend" desc="AMEND QUERY">
			<methods>
				<method name="selectMrnList" type="select" desc="VESSEL OPERATION SCHEDULE LIST"></method>
				<method name="selectMrnDetail" type="select" desc="VESSEL OPERATION SCHEDULE VIEW"></method>
				<method name="selectMblList" type="select" desc="VESSEL OPERATION AMEND BY OFFICIAL AUTHORITY  REGIST FORM"></method>
				<method name="selectMblDetail" type="select" desc="VESSEL OPERATION AMEND BY OFFICIAL AUTHORITY  REGIST"></method>
				<method name="selectHblList" type="select" desc="VESSEL OPERATION AMEND BY OFFICIAL AUTHORITY  EDIT FORM"></method>
				<method name="selectHblDetail" type="select" desc="VESSEL OPERATION AMEND BY OFFICIAL AUTHORITY  UPDATE"></method>
				<method name="registMaster" type="regist" desc="MBL/HBL AMEND BY OFFICIAL AUTHORITY REGIST FORM"></method>
				<method name="updateMaster" type="update" desc="MBL/HBL AMEND BY OFFICIAL AUTHORITY REGIST"></method>
				<method name="registBl" type="regist" desc=""></method>
				<method name="updateBl" type="update" desc=""></method>
				<method name="registCntr" type="regist" desc="MBL/HBL AMEND BY OFFICIAL AUTHORITY EDIT FORM"></method>
				<method name="updateCntr" type="update" desc="MBL/HBL AMEND BY OFFICIAL AUTHORITY UPDATE"></method>
				<method name="NoticeForm" type="regist" desc=" AMEND NOTICE FORM "></method>
				<method name="auditManifest" type="audit" desc="AMEND NOTICE"></method>
			</methods>
		</program>
	</package>
</packages>
